import { defineField, defineType } from 'sanity';

export const contactPage = defineType({
  name: 'contactPage',
  title: 'Contact Page',
  type: 'document',
  fieldsets: [
    { name: 'header', title: 'Header Section' },
    { name: 'officesSection', title: 'Offices & Locations' },
    { name: 'contactInfo', title: 'Direct Contact Info (Email & Phone Numbers)' },
    { name: 'faqSection', title: 'Frequently Asked Questions' },
  ],
  fields: [
    defineField({
      name: 'pageTitle',
      title: 'Page Title',
      type: 'string',
      fieldset: 'header',
      initialValue: 'Contact Us',
      placeholder: 'e.g. Contact Us',
      description: 'The main heading for the Contact page.',
    }),
    defineField({
      name: 'introduction',
      title: 'Introduction Text',
      type: 'text',
      fieldset: 'header',
      initialValue: 'We are here to help. Reach out to us for any inquiries or support.',
      placeholder: 'We are here to help. Reach out to us for any inquiries or support.',
      description: 'Text shown above the contact form or details.',
    }),
    defineField({
      name: 'officesTitle',
      title: 'Offices Section Heading',
      type: 'string',
      fieldset: 'officesSection',
      initialValue: 'Our Offices',
      placeholder: 'Our Offices',
    }),
    defineField({
      name: 'corporateOfficeTitle',
      title: 'Corporate Office Title',
      type: 'string',
      fieldset: 'officesSection',
      initialValue: 'Corporate Office',
      placeholder: 'Corporate Office',
    }),
    defineField({
      name: 'corporateOfficeAddress',
      title: 'Corporate Office Address',
      type: 'text',
      fieldset: 'officesSection',
      initialValue: 'New Delhi, India',
      placeholder: 'New Delhi, India',
    }),
    defineField({
      name: 'branchOfficeTitle',
      title: 'Branch Office Title',
      type: 'string',
      fieldset: 'officesSection',
      initialValue: 'Branch Office',
      placeholder: 'Branch Office',
    }),
    defineField({
      name: 'branchOfficeAddress',
      title: 'Branch Office Address',
      type: 'text',
      fieldset: 'officesSection',
      initialValue: 'Indo Japan Chamber of Commerce, C/O.AJU HOTEL GURUGRAM (Behind Star Mall), Silokhera, Sector 30, Haryana - 122 001.',
      placeholder: 'Indo Japan Chamber of Commerce, C/O.AJU HOTEL GURUGRAM (Behind Star Mall), Silokhera, Sector 30, Haryana - 122 001.',
    }),
    defineField({
      name: 'japanOfficeTitle',
      title: 'Japan Office Title',
      type: 'string',
      fieldset: 'officesSection',
      initialValue: 'Japan Representative Office',
      placeholder: 'Japan Representative Office',
    }),
    defineField({
      name: 'japanOfficeAddress',
      title: 'Japan Office Address',
      type: 'text',
      fieldset: 'officesSection',
      initialValue: 'Indo-Japan Chamber of Commerce, 3-chōme-16-1, Shibaura, Minato City, Tokyo 108-0023, Japan',
      placeholder: 'Indo-Japan Chamber of Commerce, 3-chōme-16-1, Shibaura, Minato City, Tokyo 108-0023, Japan',
    }),
    defineField({
      name: 'contactEmail',
      title: 'Contact Email Address',
      type: 'string',
      fieldset: 'contactInfo',
      initialValue: 'info@ijcc.in',
      placeholder: 'info@ijcc.in',
    }),
    defineField({
      name: 'phoneIndia',
      title: 'Primary Phone Number (India)',
      type: 'string',
      fieldset: 'contactInfo',
      initialValue: '+91-92679 19281',
      placeholder: '+91-92679 19281',
    }),
    defineField({
      name: 'phoneBranch',
      title: 'Branch Phone Number',
      type: 'string',
      fieldset: 'contactInfo',
      initialValue: '+91-9871458400 (Branch)',
      placeholder: '+91-9871458400 (Branch)',
    }),
    defineField({
      name: 'phoneJapan',
      title: 'Japan Phone Number',
      type: 'string',
      fieldset: 'contactInfo',
      initialValue: '+81-80-9055-1930 (Japan)',
      placeholder: '+81-80-9055-1930 (Japan)',
    }),
    defineField({
      name: 'faqTitle',
      title: 'FAQ Section Title',
      type: 'string',
      fieldset: 'faqSection',
      initialValue: 'Frequently Asked Questions',
      placeholder: 'Frequently Asked Questions',
    }),
    defineField({
      name: 'faqs',
      title: 'Custom FAQs List',
      type: 'array',
      fieldset: 'faqSection',
      of: [
        {
          type: 'object',
          preview: {
            select: { title: 'question', subtitle: 'answer' },
          },
          fields: [
            { name: 'question', type: 'string', title: 'Question' },
            { name: 'answer', type: 'text', title: 'Answer' },
          ],
        },
      ],
    }),
  ],
});
