import { defineField, defineType } from 'sanity';

export const membersPage = defineType({
  name: 'membersPage',
  title: 'Members Page',
  type: 'document',
  fields: [
    defineField({ name: 'associatesTitle', title: 'Associates Title', type: 'string' }),
    defineField({ name: 'associatesDescription', title: 'Associates Description', type: 'text' }),
    defineField({ name: 'paymentTitle', title: 'Payment Block Title', type: 'string' }),
    defineField({ name: 'paymentSubtitle', title: 'Payment Block Subtitle', type: 'string' }),
    defineField({ name: 'accountNameLabel', title: 'Account Name Label', type: 'string' }),
    defineField({ name: 'accountName', title: 'Account Name', type: 'string' }),
    defineField({ name: 'bankNameLabel', title: 'Bank Name Label', type: 'string' }),
    defineField({ name: 'bankName', title: 'Bank Name', type: 'string' }),
    defineField({ name: 'accountNoLabel', title: 'Account No Label', type: 'string' }),
    defineField({ name: 'accountNo', title: 'Account Number', type: 'string' }),
    defineField({ name: 'branchLabel', title: 'Branch Label', type: 'string' }),
    defineField({ name: 'branch', title: 'Branch', type: 'string' }),
    defineField({ name: 'ifscCodeLabel', title: 'IFSC Label', type: 'string' }),
    defineField({ name: 'ifscCode', title: 'IFSC Code', type: 'string' }),
    defineField({ name: 'micrCodeLabel', title: 'MICR Label', type: 'string' }),
    defineField({ name: 'micrCode', title: 'MICR Code', type: 'string' }),
    defineField({ name: 'branchCodeLabel', title: 'Branch Code Label', type: 'string' }),
    defineField({ name: 'branchCode', title: 'Branch Code', type: 'string' }),
    defineField({ name: 'qrImage', title: 'Payment QR (upload)', type: 'image' }),
    defineField({ name: 'qrImageUrl', title: 'Payment QR URL (fallback)', type: 'url' }),
    defineField({ name: 'scanLabel', title: 'Scan-to-pay Label', type: 'string' }),
    defineField({ name: 'supportText', title: 'Support Line Text', type: 'string' }),
    defineField({ name: 'paymentNote', title: 'Payment Note', type: 'text' }),
    defineField({ name: 'rulesTitle', title: 'Rules Title', type: 'string' }),
    defineField({
      name: 'rules',
      title: 'Membership Rules',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({ name: 'enrollmentTitle', title: 'Enrollment Card Title', type: 'string' }),
    defineField({ name: 'enrollmentDescription', title: 'Enrollment Card Description', type: 'text' }),
    defineField({ name: 'contactTitle', title: 'Contact Card Title', type: 'string' }),
  ],
});
